apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: karsajobs
        image: ghcr.io/naufalhanif14/karsajobs:latest
        imagePullPolicy: Always
        resources:
            limits:
              cpu: 200m
            requests:
              cpu: 100m
        ports:
        - containerPort: 8080
        env:
          - name: APP_PORT
            value: "8080"
          - name: MONGO_HOST
            value: mongo-service
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key:  MONGO_ROOT_USERNAME
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key: MONGO_ROOT_PASSWORD